// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (id, org_id, email, name, phone, tag)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, name, phone, tag, created_at, updated_at
`

type CreateContactParams struct {
	ID    string  `db:"id" json:"id"`
	OrgID string  `db:"org_id" json:"org_id"`
	Email string  `db:"email" json:"email"`
	Name  *string `db:"name" json:"name"`
	Phone *string `db:"phone" json:"phone"`
	Tag   *string `db:"tag" json:"tag"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.Tag,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1 AND org_id = $2
`

type DeleteContactParams struct {
	ID    string `db:"id" json:"id"`
	OrgID string `db:"org_id" json:"org_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.OrgID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, org_id, email, name, phone, tag, created_at, updated_at FROM contacts
WHERE id = $1 AND org_id = $2
`

type GetContactParams struct {
	ID    string `db:"id" json:"id"`
	OrgID string `db:"org_id" json:"org_id"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.OrgID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactTags = `-- name: ListContactTags :many
SELECT DISTINCT tag FROM contacts
WHERE org_id = $1 AND tag IS NOT NULL
ORDER BY tag
`

func (q *Queries) ListContactTags(ctx context.Context, orgID string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listContactTags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var tag *string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, org_id, email, name, phone, tag, created_at, updated_at FROM contacts
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContacts(ctx context.Context, orgID string) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByTag = `-- name: ListContactsByTag :many
SELECT id, org_id, email, name, phone, tag, created_at, updated_at FROM contacts
WHERE org_id = $1 AND tag = $2
ORDER BY created_at DESC
`

type ListContactsByTagParams struct {
	OrgID string  `db:"org_id" json:"org_id"`
	Tag   *string `db:"tag" json:"tag"`
}

func (q *Queries) ListContactsByTag(ctx context.Context, arg ListContactsByTagParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByTag, arg.OrgID, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = $2, phone = $3, tag = $4, updated_at = NOW()
WHERE id = $1 AND org_id = $5
RETURNING id, org_id, email, name, phone, tag, created_at, updated_at
`

type UpdateContactParams struct {
	ID    string  `db:"id" json:"id"`
	Name  *string `db:"name" json:"name"`
	Phone *string `db:"phone" json:"phone"`
	Tag   *string `db:"tag" json:"tag"`
	OrgID string  `db:"org_id" json:"org_id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Tag,
		arg.OrgID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
