// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (
    id, notification_id, organization_id, project_id, environment_id,
    channel, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at
`

type CreateDeliveryParams struct {
	ID             string              `db:"id" json:"id"`
	NotificationID string              `db:"notification_id" json:"notification_id"`
	OrganizationID string              `db:"organization_id" json:"organization_id"`
	ProjectID      string              `db:"project_id" json:"project_id"`
	EnvironmentID  string              `db:"environment_id" json:"environment_id"`
	Channel        NotificationChannel `db:"channel" json:"channel"`
	Status         NotificationStatus  `db:"status" json:"status"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.ID,
		arg.NotificationID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Channel,
		arg.Status,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveriesByNotification = `-- name: GetDeliveriesByNotification :many
SELECT id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at FROM deliveries
WHERE notification_id = $1 AND organization_id = $2
ORDER BY created_at ASC
`

type GetDeliveriesByNotificationParams struct {
	NotificationID string `db:"notification_id" json:"notification_id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetDeliveriesByNotification(ctx context.Context, arg GetDeliveriesByNotificationParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, getDeliveriesByNotification, arg.NotificationID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Channel,
			&i.ProviderType,
			&i.ProviderMessageID,
			&i.Status,
			&i.AttemptCount,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.ScheduledAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at FROM deliveries
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type GetDeliveryParams struct {
	ID             string `db:"id" json:"id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetDelivery(ctx context.Context, arg GetDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, arg.ID, arg.OrganizationID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryByProviderMessageID = `-- name: GetDeliveryByProviderMessageID :one
SELECT id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at FROM deliveries
WHERE provider_message_id = $1
LIMIT 1
`

func (q *Queries) GetDeliveryByProviderMessageID(ctx context.Context, providerMessageID *string) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByProviderMessageID, providerMessageID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryBounced = `-- name: UpdateDeliveryBounced :one
UPDATE deliveries
SET status = 'bounced', failed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at
`

func (q *Queries) UpdateDeliveryBounced(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryBounced, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryDelivered = `-- name: UpdateDeliveryDelivered :one
UPDATE deliveries
SET status = 'delivered', delivered_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at
`

func (q *Queries) UpdateDeliveryDelivered(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryDelivered, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliverySent = `-- name: UpdateDeliverySent :one
UPDATE deliveries
SET
    status              = 'sent',
    provider_type       = $2,
    provider_message_id = $3,
    sent_at             = NOW(),
    updated_at          = NOW()
WHERE id = $1
RETURNING id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at
`

type UpdateDeliverySentParams struct {
	ID                string  `db:"id" json:"id"`
	ProviderType      *string `db:"provider_type" json:"provider_type"`
	ProviderMessageID *string `db:"provider_message_id" json:"provider_message_id"`
}

func (q *Queries) UpdateDeliverySent(ctx context.Context, arg UpdateDeliverySentParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliverySent, arg.ID, arg.ProviderType, arg.ProviderMessageID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :one
UPDATE deliveries
SET status = $2, attempt_count = attempt_count + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, notification_id, organization_id, project_id, environment_id, channel, provider_type, provider_message_id, status, attempt_count, last_error_code, last_error_message, scheduled_at, sent_at, delivered_at, failed_at, created_at, updated_at
`

type UpdateDeliveryStatusParams struct {
	ID     string             `db:"id" json:"id"`
	Status NotificationStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryStatus, arg.ID, arg.Status)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ProviderMessageID,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
