// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_events.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryEvent = `-- name: CreateDeliveryEvent :one
INSERT INTO delivery_events (
    id, delivery_id, event_type, provider_type,
    provider_event_id, payload, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (provider_type, provider_event_id) DO NOTHING
RETURNING id, delivery_id, event_type, provider_type, provider_event_id, payload, occurred_at, created_at
`

type CreateDeliveryEventParams struct {
	ID              string             `db:"id" json:"id"`
	DeliveryID      string             `db:"delivery_id" json:"delivery_id"`
	EventType       DeliveryEventType  `db:"event_type" json:"event_type"`
	ProviderType    *string            `db:"provider_type" json:"provider_type"`
	ProviderEventID *string            `db:"provider_event_id" json:"provider_event_id"`
	Payload         json.RawMessage    `db:"payload" json:"payload"`
	OccurredAt      pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateDeliveryEvent(ctx context.Context, arg CreateDeliveryEventParams) (DeliveryEvent, error) {
	row := q.db.QueryRow(ctx, createDeliveryEvent,
		arg.ID,
		arg.DeliveryID,
		arg.EventType,
		arg.ProviderType,
		arg.ProviderEventID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i DeliveryEvent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.EventType,
		&i.ProviderType,
		&i.ProviderEventID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryEvents = `-- name: GetDeliveryEvents :many
SELECT id, delivery_id, event_type, provider_type, provider_event_id, payload, occurred_at, created_at FROM delivery_events
WHERE delivery_id = $1
ORDER BY occurred_at ASC
`

func (q *Queries) GetDeliveryEvents(ctx context.Context, deliveryID string) ([]DeliveryEvent, error) {
	rows, err := q.db.Query(ctx, getDeliveryEvents, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryEvent
	for rows.Next() {
		var i DeliveryEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.EventType,
			&i.ProviderType,
			&i.ProviderEventID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
