// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID        string          `db:"id" json:"id"`
	ProjectID string          `db:"project_id" json:"project_id"`
	Name      EnvironmentName `db:"name" json:"name"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ID, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductionEnvironment = `-- name: GetProductionEnvironment :one
SELECT id, project_id, name, created_at, updated_at FROM environments
WHERE project_id = $1 AND name = 'production'
LIMIT 1
`

func (q *Queries) GetProductionEnvironment(ctx context.Context, projectID string) (Environment, error) {
	row := q.db.QueryRow(ctx, getProductionEnvironment, projectID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
