// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryEventType string

const (
	DeliveryEventTypeQueued     DeliveryEventType = "queued"
	DeliveryEventTypeSent       DeliveryEventType = "sent"
	DeliveryEventTypeDelivered  DeliveryEventType = "delivered"
	DeliveryEventTypeOpened     DeliveryEventType = "opened"
	DeliveryEventTypeClicked    DeliveryEventType = "clicked"
	DeliveryEventTypeBounced    DeliveryEventType = "bounced"
	DeliveryEventTypeComplained DeliveryEventType = "complained"
	DeliveryEventTypeFailed     DeliveryEventType = "failed"
)

func (e *DeliveryEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryEventType(s)
	case string:
		*e = DeliveryEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryEventType: %T", src)
	}
	return nil
}

type NullDeliveryEventType struct {
	DeliveryEventType DeliveryEventType `json:"delivery_event_type"`
	Valid             bool              `json:"valid"` // Valid is true if DeliveryEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryEventType) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryEventType), nil
}

type EnvironmentName string

const (
	EnvironmentNameDevelopment EnvironmentName = "development"
	EnvironmentNameStaging     EnvironmentName = "staging"
	EnvironmentNameProduction  EnvironmentName = "production"
)

func (e *EnvironmentName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnvironmentName(s)
	case string:
		*e = EnvironmentName(s)
	default:
		return fmt.Errorf("unsupported scan type for EnvironmentName: %T", src)
	}
	return nil
}

type NullEnvironmentName struct {
	EnvironmentName EnvironmentName `json:"environment_name"`
	Valid           bool            `json:"valid"` // Valid is true if EnvironmentName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironmentName) Scan(value interface{}) error {
	if value == nil {
		ns.EnvironmentName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnvironmentName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironmentName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnvironmentName), nil
}

type NotificationChannel string

const (
	NotificationChannelEmail    NotificationChannel = "email"
	NotificationChannelSms      NotificationChannel = "sms"
	NotificationChannelPush     NotificationChannel = "push"
	NotificationChannelWhatsapp NotificationChannel = "whatsapp"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type NotificationStatus string

const (
	NotificationStatusQueued          NotificationStatus = "queued"
	NotificationStatusProcessing      NotificationStatus = "processing"
	NotificationStatusSent            NotificationStatus = "sent"
	NotificationStatusDelivered       NotificationStatus = "delivered"
	NotificationStatusFailedTemporary NotificationStatus = "failed_temporary"
	NotificationStatusFailedPermanent NotificationStatus = "failed_permanent"
	NotificationStatusBounced         NotificationStatus = "bounced"
	NotificationStatusComplained      NotificationStatus = "complained"
	NotificationStatusSuppressed      NotificationStatus = "suppressed"
	NotificationStatusCancelled       NotificationStatus = "cancelled"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type OrgRole string

const (
	OrgRoleOwner  OrgRole = "owner"
	OrgRoleMember OrgRole = "member"
)

func (e *OrgRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgRole(s)
	case string:
		*e = OrgRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgRole: %T", src)
	}
	return nil
}

type NullOrgRole struct {
	OrgRole OrgRole `json:"org_role"`
	Valid   bool    `json:"valid"` // Valid is true if OrgRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrgRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgRole), nil
}

type OrgType string

const (
	OrgTypePlatform OrgType = "platform"
	OrgTypeCustomer OrgType = "customer"
)

func (e *OrgType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgType(s)
	case string:
		*e = OrgType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgType: %T", src)
	}
	return nil
}

type NullOrgType struct {
	OrgType OrgType `json:"org_type"`
	Valid   bool    `json:"valid"` // Valid is true if OrgType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgType) Scan(value interface{}) error {
	if value == nil {
		ns.OrgType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgType), nil
}

type ProviderChannel string

const (
	ProviderChannelEmail ProviderChannel = "email"
	ProviderChannelSms   ProviderChannel = "sms"
	ProviderChannelPush  ProviderChannel = "push"
)

func (e *ProviderChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderChannel(s)
	case string:
		*e = ProviderChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderChannel: %T", src)
	}
	return nil
}

type NullProviderChannel struct {
	ProviderChannel ProviderChannel `json:"provider_channel"`
	Valid           bool            `json:"valid"` // Valid is true if ProviderChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderChannel), nil
}

type ProviderType string

const (
	ProviderTypeResend   ProviderType = "resend"
	ProviderTypeSendgrid ProviderType = "sendgrid"
	ProviderTypeSes      ProviderType = "ses"
	ProviderTypeTwilio   ProviderType = "twilio"
	ProviderTypeFcm      ProviderType = "fcm"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType `json:"provider_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type TemplateVersionStatus string

const (
	TemplateVersionStatusDraft    TemplateVersionStatus = "draft"
	TemplateVersionStatusActive   TemplateVersionStatus = "active"
	TemplateVersionStatusArchived TemplateVersionStatus = "archived"
)

func (e *TemplateVersionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateVersionStatus(s)
	case string:
		*e = TemplateVersionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateVersionStatus: %T", src)
	}
	return nil
}

type NullTemplateVersionStatus struct {
	TemplateVersionStatus TemplateVersionStatus `json:"template_version_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if TemplateVersionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateVersionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateVersionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateVersionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateVersionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateVersionStatus), nil
}

type ApiKey struct {
	ID             string             `db:"id" json:"id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Name           string             `db:"name" json:"name"`
	KeyPrefix      string             `db:"key_prefix" json:"key_prefix"`
	KeyHash        string             `db:"key_hash" json:"key_hash"`
	Scopes         []string           `db:"scopes" json:"scopes"`
	LastUsedAt     pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Delivery struct {
	ID                string              `db:"id" json:"id"`
	NotificationID    string              `db:"notification_id" json:"notification_id"`
	OrganizationID    string              `db:"organization_id" json:"organization_id"`
	ProjectID         string              `db:"project_id" json:"project_id"`
	EnvironmentID     string              `db:"environment_id" json:"environment_id"`
	Channel           NotificationChannel `db:"channel" json:"channel"`
	ProviderType      *string             `db:"provider_type" json:"provider_type"`
	ProviderMessageID *string             `db:"provider_message_id" json:"provider_message_id"`
	Status            NotificationStatus  `db:"status" json:"status"`
	AttemptCount      int32               `db:"attempt_count" json:"attempt_count"`
	LastErrorCode     *string             `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage  *string             `db:"last_error_message" json:"last_error_message"`
	ScheduledAt       pgtype.Timestamptz  `db:"scheduled_at" json:"scheduled_at"`
	SentAt            pgtype.Timestamptz  `db:"sent_at" json:"sent_at"`
	DeliveredAt       pgtype.Timestamptz  `db:"delivered_at" json:"delivered_at"`
	FailedAt          pgtype.Timestamptz  `db:"failed_at" json:"failed_at"`
	CreatedAt         pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type DeliveryEvent struct {
	ID              string             `db:"id" json:"id"`
	DeliveryID      string             `db:"delivery_id" json:"delivery_id"`
	EventType       DeliveryEventType  `db:"event_type" json:"event_type"`
	ProviderType    *string            `db:"provider_type" json:"provider_type"`
	ProviderEventID *string            `db:"provider_event_id" json:"provider_event_id"`
	Payload         json.RawMessage    `db:"payload" json:"payload"`
	OccurredAt      pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Environment struct {
	ID        string             `db:"id" json:"id"`
	ProjectID string             `db:"project_id" json:"project_id"`
	Name      EnvironmentName    `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Notification struct {
	ID             string              `db:"id" json:"id"`
	OrganizationID string              `db:"organization_id" json:"organization_id"`
	ProjectID      string              `db:"project_id" json:"project_id"`
	EnvironmentID  string              `db:"environment_id" json:"environment_id"`
	ExternalID     *string             `db:"external_id" json:"external_id"`
	TemplateKey    *string             `db:"template_key" json:"template_key"`
	Channel        NotificationChannel `db:"channel" json:"channel"`
	RecipientRef   *string             `db:"recipient_ref" json:"recipient_ref"`
	Status         NotificationStatus  `db:"status" json:"status"`
	Metadata       json.RawMessage     `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type Organization struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Type      OrgType            `db:"type" json:"type"`
}

type OrganizationMember struct {
	ID        string             `db:"id" json:"id"`
	OrgID     string             `db:"org_id" json:"org_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Role      OrgRole            `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Project struct {
	ID             string             `db:"id" json:"id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Name           string             `db:"name" json:"name"`
	Slug           string             `db:"slug" json:"slug"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	IsDefault      bool               `db:"is_default" json:"is_default"`
}

type ProviderConnection struct {
	ID              string             `db:"id" json:"id"`
	OrganizationID  string             `db:"organization_id" json:"organization_id"`
	ProjectID       string             `db:"project_id" json:"project_id"`
	EnvironmentID   string             `db:"environment_id" json:"environment_id"`
	ProviderType    ProviderType       `db:"provider_type" json:"provider_type"`
	Channel         ProviderChannel    `db:"channel" json:"channel"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	EncryptedConfig string             `db:"encrypted_config" json:"encrypted_config"`
	IsDefault       bool               `db:"is_default" json:"is_default"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID               string             `db:"id" json:"id"`
	UserID           string             `db:"user_id" json:"user_id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OrgID            string             `db:"org_id" json:"org_id"`
}

type Template struct {
	ID             string              `db:"id" json:"id"`
	OrganizationID string              `db:"organization_id" json:"organization_id"`
	ProjectID      string              `db:"project_id" json:"project_id"`
	Key            string              `db:"key" json:"key"`
	Name           string              `db:"name" json:"name"`
	Channel        NotificationChannel `db:"channel" json:"channel"`
	ActiveVersion  *int32              `db:"active_version" json:"active_version"`
	CreatedAt      pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type TemplateVersion struct {
	ID              string                `db:"id" json:"id"`
	TemplateID      string                `db:"template_id" json:"template_id"`
	VersionNumber   int32                 `db:"version_number" json:"version_number"`
	Subject         *string               `db:"subject" json:"subject"`
	HtmlBody        *string               `db:"html_body" json:"html_body"`
	TextBody        *string               `db:"text_body" json:"text_body"`
	SmsBody         *string               `db:"sms_body" json:"sms_body"`
	VariablesSchema json.RawMessage       `db:"variables_schema" json:"variables_schema"`
	Status          TemplateVersionStatus `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz    `db:"created_at" json:"created_at"`
}

type User struct {
	ID           string             `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
