// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"encoding/json"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id, organization_id, project_id, environment_id,
    external_id, template_key, channel, recipient_ref,
    status, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, organization_id, project_id, environment_id, external_id, template_key, channel, recipient_ref, status, metadata, created_at, updated_at
`

type CreateNotificationParams struct {
	ID             string              `db:"id" json:"id"`
	OrganizationID string              `db:"organization_id" json:"organization_id"`
	ProjectID      string              `db:"project_id" json:"project_id"`
	EnvironmentID  string              `db:"environment_id" json:"environment_id"`
	ExternalID     *string             `db:"external_id" json:"external_id"`
	TemplateKey    *string             `db:"template_key" json:"template_key"`
	Channel        NotificationChannel `db:"channel" json:"channel"`
	RecipientRef   *string             `db:"recipient_ref" json:"recipient_ref"`
	Status         NotificationStatus  `db:"status" json:"status"`
	Metadata       json.RawMessage     `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.TemplateKey,
		arg.Channel,
		arg.RecipientRef,
		arg.Status,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.TemplateKey,
		&i.Channel,
		&i.RecipientRef,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, organization_id, project_id, environment_id, external_id, template_key, channel, recipient_ref, status, metadata, created_at, updated_at FROM notifications
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type GetNotificationParams struct {
	ID             string `db:"id" json:"id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.OrganizationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.TemplateKey,
		&i.Channel,
		&i.RecipientRef,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, project_id, environment_id, external_id, template_key, channel, recipient_ref, status, metadata, created_at, updated_at
`

type UpdateNotificationStatusParams struct {
	ID     string             `db:"id" json:"id"`
	Status NotificationStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus, arg.ID, arg.Status)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.TemplateKey,
		&i.Channel,
		&i.RecipientRef,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
