// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrgInvite = `-- name: CreateOrgInvite :one
INSERT INTO org_invites (id, org_id, created_by, token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, created_by, token, used_at, expires_at, created_at
`

type CreateOrgInviteParams struct {
	ID        string             `db:"id" json:"id"`
	OrgID     string             `db:"org_id" json:"org_id"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateOrgInvite(ctx context.Context, arg CreateOrgInviteParams) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, createOrgInvite,
		arg.ID,
		arg.OrgID,
		arg.CreatedBy,
		arg.Token,
		arg.ExpiresAt,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Token,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgInviteByToken = `-- name: GetOrgInviteByToken :one
SELECT id, org_id, created_by, token, used_at, expires_at, created_at FROM org_invites WHERE token = $1
`

func (q *Queries) GetOrgInviteByToken(ctx context.Context, token string) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, getOrgInviteByToken, token)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Token,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgInvites = `-- name: ListOrgInvites :many
SELECT id, org_id, created_by, token, used_at, expires_at, created_at FROM org_invites WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrgInvites(ctx context.Context, orgID string) ([]OrgInvite, error) {
	rows, err := q.db.Query(ctx, listOrgInvites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvite
	for rows.Next() {
		var i OrgInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedBy,
			&i.Token,
			&i.UsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrgInviteUsed = `-- name: MarkOrgInviteUsed :one
UPDATE org_invites SET used_at = NOW() WHERE id = $1 RETURNING id, org_id, created_by, token, used_at, expires_at, created_at
`

func (q *Queries) MarkOrgInviteUsed(ctx context.Context, id string) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, markOrgInviteUsed, id)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Token,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
