// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_members.sql

package db

import (
	"context"
)

const createOrgMember = `-- name: CreateOrgMember :one
INSERT INTO organization_members (id, org_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, user_id, role, created_at, updated_at
`

type CreateOrgMemberParams struct {
	ID     string  `db:"id" json:"id"`
	OrgID  string  `db:"org_id" json:"org_id"`
	UserID string  `db:"user_id" json:"user_id"`
	Role   OrgRole `db:"role" json:"role"`
}

func (q *Queries) CreateOrgMember(ctx context.Context, arg CreateOrgMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrgMember,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM organization_members WHERE org_id = $1 AND user_id = $2
`

type DeleteOrgMemberParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMember, arg.OrgID, arg.UserID)
	return err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT id, org_id, user_id, role, created_at, updated_at FROM organization_members
WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT id, org_id, user_id, role, created_at, updated_at FROM organization_members
WHERE org_id = $1
ORDER BY created_at
`

func (q *Queries) ListOrgMembers(ctx context.Context, orgID string) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMember
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrgs = `-- name: ListUserOrgs :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, o.type, o.is_active, o.website, o.description FROM organizations o
JOIN organization_members m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.name
`

func (q *Queries) ListUserOrgs(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listUserOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.IsActive,
			&i.Website,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
