// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug, type, website, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, created_at, updated_at, type, is_active, website, description
`

type CreateOrganizationParams struct {
	ID          string  `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Slug        string  `db:"slug" json:"slug"`
	Type        OrgType `db:"type" json:"type"`
	Website     *string `db:"website" json:"website"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Website,
		arg.Description,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.IsActive,
		&i.Website,
		&i.Description,
	)
	return i, err
}

const getOrgStats = `-- name: GetOrgStats :one
SELECT
    (SELECT COUNT(*) FROM api_keys      WHERE api_keys.organization_id = $1 AND revoked_at IS NULL) AS api_key_count,
    (SELECT COUNT(*) FROM notifications WHERE notifications.organization_id = $1)                    AS call_count
`

type GetOrgStatsRow struct {
	ApiKeyCount int64 `db:"api_key_count" json:"api_key_count"`
	CallCount   int64 `db:"call_count" json:"call_count"`
}

func (q *Queries) GetOrgStats(ctx context.Context, organizationID string) (GetOrgStatsRow, error) {
	row := q.db.QueryRow(ctx, getOrgStats, organizationID)
	var i GetOrgStatsRow
	err := row.Scan(&i.ApiKeyCount, &i.CallCount)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at, updated_at, type, is_active, website, description FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.IsActive,
		&i.Website,
		&i.Description,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at, type, is_active, website, description FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.IsActive,
		&i.Website,
		&i.Description,
	)
	return i, err
}

const getPlatformOrg = `-- name: GetPlatformOrg :one
SELECT id, name, slug, created_at, updated_at, type, is_active, website, description FROM organizations WHERE type = 'platform' LIMIT 1
`

func (q *Queries) GetPlatformOrg(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getPlatformOrg)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.IsActive,
		&i.Website,
		&i.Description,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, created_at, updated_at, type, is_active, website, description FROM organizations ORDER BY name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.IsActive,
			&i.Website,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformOrgExists = `-- name: PlatformOrgExists :one
SELECT EXISTS(SELECT 1 FROM organizations WHERE type = 'platform') AS exists
`

func (q *Queries) PlatformOrgExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, platformOrgExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setOrgActive = `-- name: SetOrgActive :one
UPDATE organizations
SET is_active  = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, created_at, updated_at, type, is_active, website, description
`

type SetOrgActiveParams struct {
	ID       string `db:"id" json:"id"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) SetOrgActive(ctx context.Context, arg SetOrgActiveParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrgActive, arg.ID, arg.IsActive)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.IsActive,
		&i.Website,
		&i.Description,
	)
	return i, err
}
