// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, organization_id, name, slug, is_default)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, name, slug, created_at, updated_at, is_default
`

type CreateProjectParams struct {
	ID             string `db:"id" json:"id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
	Name           string `db:"name" json:"name"`
	Slug           string `db:"slug" json:"slug"`
	IsDefault      bool   `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.IsDefault,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getDefaultProject = `-- name: GetDefaultProject :one
SELECT id, organization_id, name, slug, created_at, updated_at, is_default FROM projects
WHERE organization_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultProject(ctx context.Context, organizationID string) (Project, error) {
	row := q.db.QueryRow(ctx, getDefaultProject, organizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}
