// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_connections.sql

package db

import (
	"context"
)

const createProviderConnection = `-- name: CreateProviderConnection :one
INSERT INTO provider_connections (
    id, organization_id, project_id, environment_id,
    provider_type, channel, display_name, encrypted_config, is_default
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, project_id, environment_id, provider_type, channel, display_name, encrypted_config, is_default, is_active, created_at, updated_at
`

type CreateProviderConnectionParams struct {
	ID              string          `db:"id" json:"id"`
	OrganizationID  string          `db:"organization_id" json:"organization_id"`
	ProjectID       string          `db:"project_id" json:"project_id"`
	EnvironmentID   string          `db:"environment_id" json:"environment_id"`
	ProviderType    ProviderType    `db:"provider_type" json:"provider_type"`
	Channel         ProviderChannel `db:"channel" json:"channel"`
	DisplayName     string          `db:"display_name" json:"display_name"`
	EncryptedConfig string          `db:"encrypted_config" json:"encrypted_config"`
	IsDefault       bool            `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateProviderConnection(ctx context.Context, arg CreateProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, createProviderConnection,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ProviderType,
		arg.Channel,
		arg.DisplayName,
		arg.EncryptedConfig,
		arg.IsDefault,
	)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ProviderType,
		&i.Channel,
		&i.DisplayName,
		&i.EncryptedConfig,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderConnection = `-- name: DeleteProviderConnection :exec
DELETE FROM provider_connections
WHERE id = $1 AND organization_id = $2
`

type DeleteProviderConnectionParams struct {
	ID             string `db:"id" json:"id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DeleteProviderConnection(ctx context.Context, arg DeleteProviderConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteProviderConnection, arg.ID, arg.OrganizationID)
	return err
}

const getDefaultProvider = `-- name: GetDefaultProvider :one
SELECT id, organization_id, project_id, environment_id, provider_type, channel, display_name, encrypted_config, is_default, is_active, created_at, updated_at FROM provider_connections
WHERE organization_id = $1
  AND project_id      = $2
  AND environment_id  = $3
  AND channel         = $4
  AND is_default      = true
  AND is_active       = true
LIMIT 1
`

type GetDefaultProviderParams struct {
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	ProjectID      string          `db:"project_id" json:"project_id"`
	EnvironmentID  string          `db:"environment_id" json:"environment_id"`
	Channel        ProviderChannel `db:"channel" json:"channel"`
}

func (q *Queries) GetDefaultProvider(ctx context.Context, arg GetDefaultProviderParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, getDefaultProvider,
		arg.OrganizationID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Channel,
	)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ProviderType,
		&i.Channel,
		&i.DisplayName,
		&i.EncryptedConfig,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderConnection = `-- name: GetProviderConnection :one
SELECT id, organization_id, project_id, environment_id, provider_type, channel, display_name, encrypted_config, is_default, is_active, created_at, updated_at FROM provider_connections
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type GetProviderConnectionParams struct {
	ID             string `db:"id" json:"id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetProviderConnection(ctx context.Context, arg GetProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRow(ctx, getProviderConnection, arg.ID, arg.OrganizationID)
	var i ProviderConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ProviderType,
		&i.Channel,
		&i.DisplayName,
		&i.EncryptedConfig,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderConnections = `-- name: ListProviderConnections :many
SELECT id, organization_id, project_id, environment_id, provider_type, channel, display_name, encrypted_config, is_default, is_active, created_at, updated_at FROM provider_connections
WHERE organization_id = $1 AND project_id = $2 AND environment_id = $3
ORDER BY created_at DESC
`

type ListProviderConnectionsParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	ProjectID      string `db:"project_id" json:"project_id"`
	EnvironmentID  string `db:"environment_id" json:"environment_id"`
}

func (q *Queries) ListProviderConnections(ctx context.Context, arg ListProviderConnectionsParams) ([]ProviderConnection, error) {
	rows, err := q.db.Query(ctx, listProviderConnections, arg.OrganizationID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderConnection
	for rows.Next() {
		var i ProviderConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ProviderType,
			&i.Channel,
			&i.DisplayName,
			&i.EncryptedConfig,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
