// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token_hash, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID               string             `db:"id" json:"id"`
	UserID           string             `db:"user_id" json:"user_id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByRefreshTokenHash = `-- name: DeleteSessionByRefreshTokenHash :exec
DELETE FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByRefreshTokenHash, refreshTokenHash)
	return err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, expires_at, created_at, updated_at FROM sessions
WHERE refresh_token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET refresh_token_hash = $2,
    expires_at         = $3,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, user_id, refresh_token_hash, expires_at, created_at, updated_at
`

type RotateSessionParams struct {
	ID               string             `db:"id" json:"id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
