// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"
	"encoding/json"
)

const activateTemplateVersion = `-- name: ActivateTemplateVersion :one
UPDATE template_versions
SET status = 'active'
WHERE template_id = $1 AND version_number = $2
RETURNING id, template_id, version_number, subject, html_body, text_body, sms_body, variables_schema, status, created_at, editor_blocks
`

type ActivateTemplateVersionParams struct {
	TemplateID    string `db:"template_id" json:"template_id"`
	VersionNumber int32  `db:"version_number" json:"version_number"`
}

func (q *Queries) ActivateTemplateVersion(ctx context.Context, arg ActivateTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, activateTemplateVersion, arg.TemplateID, arg.VersionNumber)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.SmsBody,
		&i.VariablesSchema,
		&i.Status,
		&i.CreatedAt,
		&i.EditorBlocks,
	)
	return i, err
}

const archiveTemplateVersions = `-- name: ArchiveTemplateVersions :exec
UPDATE template_versions
SET status = 'archived'
WHERE template_id = $1 AND status = 'active'
`

func (q *Queries) ArchiveTemplateVersions(ctx context.Context, templateID string) error {
	_, err := q.db.Exec(ctx, archiveTemplateVersions, templateID)
	return err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (id, organization_id, project_id, key, name, channel)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, project_id, key, name, channel, active_version, created_at, updated_at
`

type CreateTemplateParams struct {
	ID             string              `db:"id" json:"id"`
	OrganizationID string              `db:"organization_id" json:"organization_id"`
	ProjectID      string              `db:"project_id" json:"project_id"`
	Key            string              `db:"key" json:"key"`
	Name           string              `db:"name" json:"name"`
	Channel        NotificationChannel `db:"channel" json:"channel"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Channel,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Channel,
		&i.ActiveVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateVersion = `-- name: CreateTemplateVersion :one
INSERT INTO template_versions (
    id, template_id, version_number,
    subject, html_body, text_body, sms_body, variables_schema, editor_blocks
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, template_id, version_number, subject, html_body, text_body, sms_body, variables_schema, status, created_at, editor_blocks
`

type CreateTemplateVersionParams struct {
	ID              string          `db:"id" json:"id"`
	TemplateID      string          `db:"template_id" json:"template_id"`
	VersionNumber   int32           `db:"version_number" json:"version_number"`
	Subject         *string         `db:"subject" json:"subject"`
	HtmlBody        *string         `db:"html_body" json:"html_body"`
	TextBody        *string         `db:"text_body" json:"text_body"`
	SmsBody         *string         `db:"sms_body" json:"sms_body"`
	VariablesSchema json.RawMessage `db:"variables_schema" json:"variables_schema"`
	EditorBlocks    *string         `db:"editor_blocks" json:"editor_blocks"`
}

func (q *Queries) CreateTemplateVersion(ctx context.Context, arg CreateTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, createTemplateVersion,
		arg.ID,
		arg.TemplateID,
		arg.VersionNumber,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.SmsBody,
		arg.VariablesSchema,
		arg.EditorBlocks,
	)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.SmsBody,
		&i.VariablesSchema,
		&i.Status,
		&i.CreatedAt,
		&i.EditorBlocks,
	)
	return i, err
}

const getActiveTemplateVersion = `-- name: GetActiveTemplateVersion :one
SELECT tv.id, tv.template_id, tv.version_number, tv.subject, tv.html_body, tv.text_body, tv.sms_body, tv.variables_schema, tv.status, tv.created_at, tv.editor_blocks FROM template_versions tv
JOIN templates t ON t.id = tv.template_id
WHERE t.organization_id = $1
  AND t.project_id      = $2
  AND t.key             = $3
  AND tv.version_number = t.active_version
LIMIT 1
`

type GetActiveTemplateVersionParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	ProjectID      string `db:"project_id" json:"project_id"`
	Key            string `db:"key" json:"key"`
}

func (q *Queries) GetActiveTemplateVersion(ctx context.Context, arg GetActiveTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, getActiveTemplateVersion, arg.OrganizationID, arg.ProjectID, arg.Key)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.SmsBody,
		&i.VariablesSchema,
		&i.Status,
		&i.CreatedAt,
		&i.EditorBlocks,
	)
	return i, err
}

const getTemplateByKey = `-- name: GetTemplateByKey :one
SELECT id, organization_id, project_id, key, name, channel, active_version, created_at, updated_at FROM templates
WHERE organization_id = $1 AND project_id = $2 AND key = $3
LIMIT 1
`

type GetTemplateByKeyParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	ProjectID      string `db:"project_id" json:"project_id"`
	Key            string `db:"key" json:"key"`
}

func (q *Queries) GetTemplateByKey(ctx context.Context, arg GetTemplateByKeyParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByKey, arg.OrganizationID, arg.ProjectID, arg.Key)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Channel,
		&i.ActiveVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT id, template_id, version_number, subject, html_body, text_body, sms_body, variables_schema, status, created_at, editor_blocks FROM template_versions
WHERE template_id = $1 AND version_number = $2
LIMIT 1
`

type GetTemplateVersionParams struct {
	TemplateID    string `db:"template_id" json:"template_id"`
	VersionNumber int32  `db:"version_number" json:"version_number"`
}

func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, getTemplateVersion, arg.TemplateID, arg.VersionNumber)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.SmsBody,
		&i.VariablesSchema,
		&i.Status,
		&i.CreatedAt,
		&i.EditorBlocks,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, organization_id, project_id, key, name, channel, active_version, created_at, updated_at FROM templates
WHERE organization_id = $1 AND project_id = $2
ORDER BY created_at DESC
`

type ListTemplatesParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	ProjectID      string `db:"project_id" json:"project_id"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Channel,
			&i.ActiveVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVersionNumber = `-- name: NextVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) + 1 AS next
FROM template_versions
WHERE template_id = $1
`

func (q *Queries) NextVersionNumber(ctx context.Context, templateID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNumber, templateID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const setActiveVersion = `-- name: SetActiveVersion :one
UPDATE templates
SET active_version = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, project_id, key, name, channel, active_version, created_at, updated_at
`

type SetActiveVersionParams struct {
	ID            string `db:"id" json:"id"`
	ActiveVersion *int32 `db:"active_version" json:"active_version"`
}

func (q *Queries) SetActiveVersion(ctx context.Context, arg SetActiveVersionParams) (Template, error) {
	row := q.db.QueryRow(ctx, setActiveVersion, arg.ID, arg.ActiveVersion)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Channel,
		&i.ActiveVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
